version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - npm install -g n
      - n latest
      - npm update -g npm
      - npm install
      - npm -g --unsafe-perm install node-sass
      - npm install --unsafe-perm -g @angular/cli@1.4.9
      - npm install
  build:
    commands:
      - ng build
  post_build:
    commands:
      - aws s3 sync dist s3://vote-uploader/site --delete


